project/flash/Flash/Models/Deck.cs
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;
using Flash.Models.Identity;

namespace Flash.Models;

[Table("Deck")]
[Index("Name", Name = "IX_Deck_Name", IsUnique = false)]
[Index("UserId", "Name", Name = "IX_Deck_UserId_Name", IsUnique = true)]
public partial class Deck
{
    [Key]
    public int Id { get; set; }

    public int UserId { get; set; }

    [Required]
    [StringLength(255)]
    public string Name { get; set; } = default!;

    public int? FlashcardsCount { get; set; }

    public float? SuccessRetentionRate { get; set; }

    public float? DifficultyRetentionRate { get; set; }

    [Column(TypeName = "date")]
    public DateTime CreationDate { get; set; }

    [InverseProperty("Deck")]
    public virtual ICollection<Flashcard> Flashcards { get; } = new List<Flashcard>();

    [ForeignKey("UserId")]
    [InverseProperty("Decks")]
    public virtual User User { get; set; } = default!;
}

project/flash/Flash/Models/Flashcard.cs
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Flash.Models;

[Table("Flashcard")]
public partial class Flashcard
{
    [Key]
    public int Id { get; set; }

    public int DeckId { get; set; }

    [Required]
    public string Front { get; set; } = default!;

    [Required]
    public string Back { get; set; } = default!;

    [Column(TypeName = "date")]
    public DateTime CreationDate { get; set; }

    [Column(TypeName = "date")]
    public DateTime? RepetitionDate { get; set; }

    public int? RepetitionInterval { get; set; }

    [ForeignKey("DeckId")]
    [InverseProperty("Flashcards")]
    public virtual Deck Deck { get; set; } = default!;
}

project/flash/Flash/Pages/Decks.cshtml.cs
using Flash.Infrastructure;
using Flash.Models;
using Flash.Models.ViewModels;
using Flash.Services;
using Flash.Services.Repositories;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace Flash.Pages
{
    [Authorize]
    public class DecksModel : PageModel
    {
        private readonly IConfiguration _config;
        private readonly IDeckRepository _deckRepo;
        private readonly ISessionManagement _session;

        public static int UserId { get; set; }

        public static bool DeckExists { get; set; }

        public Pagination Pagination { get; set; } = default!;

        public string DeckIdKey { get; set; }

        public int SelectedDeckId { get; set; }

        public string? SearchTerm { get; set; }

        public IEnumerable<Deck> Decks { get; set; } = Enumerable.Empty<Deck>();

        [BindProperty]
        public Deck DeckPost { get; set; } = default!;

        public DecksModel(IConfiguration config, IDeckRepository deckRepo, ISessionManagement session)
        {
            _config = config;
            _deckRepo = deckRepo;
            _session = session;
            DeckIdKey = _config["SessionKeys:Deck"] ?? throw new InvalidOperationException();
        }

        public IActionResult OnGet(int pageNumber = 1, string? searchTerm = null)
        {
            UserId = HttpContext.User.GetClaimIntValue(_config["UserClaims:UserId"]);
            Decks = _deckRepo.GetDecksPartitioned(UserId, pageNumber, searchTerm, out int pageCount);
            if (!Decks.Any() && pageCount != 0)
            {   
                return RedirectToPage(new { pageNumber = pageCount, searchTerm });
            }

            SearchTerm = searchTerm;
            Pagination = new(pageNumber, pageCount, "/Decks");
            Deck? deck = _session.SetDefaultDeck(HttpContext.Session, Decks);
            SelectedDeckId = deck?.Id ?? 0;
            return Page();
        }

        public async Task<IActionResult> OnPostAsync(string returnUrl)
        {
            if (string.IsNullOrEmpty(DeckPost.Name))
            {
                return Redirect(returnUrl);
            }

            try
            {
                await _deckRepo.AddAsync(DeckPost);
            }
            catch (InvalidOperationException)
            {
                DeckExists = true;
            }

            return Redirect(returnUrl);
        }

        public async Task<IActionResult> OnPostDeleteAsync(int deckId, string returnUrl)
        {
            await _deckRepo.DeleteAsync(deckId);
            Deck? deck = HttpContext.Session.Get<Deck>(DeckIdKey);
            if (deck?.Id == deckId)
            {
                HttpContext.Session.Remove(DeckIdKey);
            }

            return Redirect(returnUrl);
        }

        public async Task<IActionResult> OnPostSelect(int deckId, string returnUrl)
        {
            Deck? deck = await _deckRepo.GetAsync(deckId);
            HttpContext.Session.Set(DeckIdKey, deck);
            return Redirect(returnUrl);
        }
    }
}

project/flash/Flash/Pages/Shared/_CompactFlashcard.cshtml
@using Flash.Models.ViewModels
@model CardOnBrowsePage
@{
    string? returnUrl = Url.Page("/Card/Browse", new 
    {
        pageNumber = Model.Page,
        searchTerm = Model.SearchTerm
    });
}

<div class="flashcard-info">
    <div class="front-info">
        <div class="more-button" onclick="showAdditionalFunctionality(this)"><span></span></div>
        @Model.Flashcard.Front
        <div class="more-interface more-interface-fixed _hidden">
            <form asp-page="/Card/Delete" class="deletion-form" method="post">
                <input type="hidden" name="flashcardId" value="@Model.Flashcard.Id" />
                <input type="hidden" name="returnUrl" value="@returnUrl" />
                <button tabindex="-1" type="submit" class="button more-interface-button more-inerface-browse-button">Delete</button>
            </form>
            <form asp-page="/Card/Edit" method="get">
                <input type="hidden" name="flashcardId" value="@Model.Flashcard.Id" />
                <input type="hidden" name="returnUrl" value="@returnUrl" />
                <button tabindex="-1" type="submit" class="button more-interface-button more-inerface-browse-button">Edit</button>
            </form>
        </div>
    </div>
    <div class="back-info">
        @Model.Flashcard.Back
        <div class="flashcard-dates">
            <span>Creation date: @($"{Model.Flashcard.CreationDate:d}")</span>
            <span>Due date: @($"{Model.Flashcard.RepetitionDate:d}")</span>
        </div>
    </div>
</div>

project/flash/Flash/Pages/Shared/_Deck.cshtml
@using Flash.Models.ViewModels
@model DeckOnPage
@{
    string? returnUrl = Url.Page("/Decks", new 
    {
        pageNumber = Model.Page,
        searchTerm = Model.SearchTerm
    });
    Dictionary<string, string?> routeValues = new()
    {
        { "deckId", Model.Deck.Id.ToString() },
        { "returnUrl", returnUrl }
    };
}
<div class="deck-block">
    <form method="post" asp-page-handler="select" asp-all-route-data="routeValues" class="deck-selector-form">
        <button type="submit">@Model.Deck.Name</button>
    </form>
    <form method="post" asp-page-handler="delete" asp-all-route-data="routeValues">
        <button type="submit" class="button delete-button">Delete</button>
    </form> 
</div>

project/flash/Flash/Pages/Shared/_Flashcard.cshtml
@using Flash.Models.ViewModels
@using Flash.Models
@using Flash.Services
@model CardOnRehearsePage
@inject ITimeInterval Interval
@{
    int hardInterval = Interval.GetNewInterval
    (
        RetentionDifficulty.Hard,
        Model.Deck.DifficultyRetentionRate!.Value,
        Model.Flashcard.RepetitionInterval!.Value
    );

    int goodInterval = Interval.GetNewInterval
    (
        RetentionDifficulty.Good,
        Model.Deck.SuccessRetentionRate!.Value,
        Model.Flashcard.RepetitionInterval!.Value
    );

    string? returnUrl = Url.Page("/Index", new { pageNumber = Model.Page });
}

<div class="flashcard">
    <div class="flashcard-front">
        <div class="flashcard-page-content">
            <div class="more-button" onclick="showAdditionalFunctionality(this)"><span></span></div>
            <p class="flashcard-front-text">@Model.Flashcard.Front</p>
            <div class="more-interface _hidden">
                <form asp-page="/Card/Delete" class="deletion-form" method="post">
                    <input type="hidden" name="flashcardId" value="@Model.Flashcard.Id" />
                    <input type="hidden" name="returnUrl" value="@returnUrl" />
                    <button tabindex="-1" type="submit" class="button more-interface-button">Delete</button>
                </form>
                <form asp-page="/Card/Edit" method="get">
                    <input type="hidden" name="flashcardId" value="@Model.Flashcard.Id" />
                    <input type="hidden" name="returnUrl" value="@returnUrl" />
                    <button tabindex="-1" type="submit" class="button more-interface-button">Edit</button>
                </form>
            </div>
        </div>
        <button class="button flashcard-show-button" onclick="flipCard(this)">Show</button>
    </div>
    <div class="flashcard-back">
        <div class="flashcard-page-content">
            <div class="more-button" onclick="showAdditionalFunctionality(this)"><span></span></div>
            <p class="flashcard-back-text">@Model.Flashcard.Back</p>
            <div class="more-interface _hidden">
                <form asp-page="/Card/Delete" class="deletion-form" method="post">
                    <input type="hidden" name="flashcardId" value="@Model.Flashcard.Id" />
                    <input type="hidden" name="returnUrl" value="@returnUrl" />
                    <button tabindex="-1" type="submit" class="button more-interface-button">Delete</button>
                </form>
                <form asp-page="/Card/Edit" method="get">
                    <input type="hidden" name="flashcardId" value="@Model.Flashcard.Id" />
                    <input type="hidden" name="returnUrl" value="@returnUrl" />
                    <button tabindex="-1" type="submit" class="button more-interface-button">Edit</button>
                </form>
                <button class="button more-interface-button" onclick="flipCard(this)">Flip</button>
            </div>
        </div>
        <div class="flashcard-back-buttons">
            <form asp-route-newInterval="0" method="post">
                <input type="hidden" name="flashcardId" value="@Model.Flashcard.Id" />
                <button class="button flashcard-failure-button">
                    Again<br />
                    <span class="repetition-interval">(0d.)</span>
                </button>
            </form>
            <form asp-route-newInterval="@hardInterval" method="post">
                <input type="hidden" name="flashcardId" value="@Model.Flashcard.Id" />
                <button class="button flashcard-difficulty-button">
                    Hard<br />
                    <span class="repetition-interval">(@Interval.GetTimeInterval(hardInterval))</span>
                </button>
            </form>
            <form asp-route-newInterval="@goodInterval" method="post">
                <input type="hidden" name="flashcardId" value="@Model.Flashcard.Id" />
                <button class="button flashcard-success-button">
                    Good<br />
                    <span class="repetition-interval">(@Interval.GetTimeInterval(goodInterval))</span>
                </button>
            </form>
        </div>
    </div>
</div>

project/flash/Flash/Pages/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="~/css/style.css">
    <link rel="stylesheet" href="~/css/normalize.css">
    <title>@ViewBag.Title</title>
</head>
<body>
    <header class="page-header">
        <div class="page-header-content">
            <a class="logo" asp-page="/Index">FLASH</a>
            <nav class="header-nav">
                <a asp-page="/Decks" class="nav-link">Decks</a>
                <a asp-page="/Card/Add" class="nav-link">Add</a>
                <div class="page-header-nav">
                    <div class="page-header-nav-left">
                        <a asp-page="/Index" class="nav-link">Rehearse</a>
                        <a asp-page="/Card/Browse" class="nav-link">Browse</a>
                    </div>
                    <div class="page-header-nav-right">
                        <button class="nav-link profile-button" onclick="showProfileInterface()">Profile</button>
                        <div class="profile-interface _hidden">
                            <a asp-page="/Settings" class="nav-link">Settings</a>
                            <a asp-area="Identity" asp-page="/Logout" class="nav-link">Log out</a>
                        </div>
                    </div>
                </div>
            </nav>
            <div class="burger-menu"><span></span></div>
        </div>
    </header>
    <main class="main-content">
        @RenderBody()
    </main>
    <script src="~/js/script.js"></script>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>









@*

                        <!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="~/css/style.css">
    <link rel="stylesheet" href="~/css/normalize.css">
    <title>@ViewBag.Title</title>
</head>
<body>
    <header class="page-header">
        <div class="page-header-content">
            <a class="logo" asp-page="/Index">FLASH</a>
            <div class="burger-menu"><span></span></div>
            <nav class="page-header-nav">
                <div class="page-header-nav-left">
                    <a asp-page="/Decks" class="nav-link">Decks</a>
                    <a asp-page="/Index" class="nav-link">Rehearse</a>
                    <a asp-page="/Card/Add" class="nav-link">Add</a>
                    <a asp-page="/Card/Browse" class="nav-link">Browse</a>
                </div>
                <div class="page-header-nav-right">
                    <button class="nav-link profile-button" onclick="showProfileInterface()">Profile</button>
                    <div class="profile-interface _hidden">
                        <a asp-page="/Settings" class="nav-link">Settings</a>
                        <a asp-area="Identity" asp-page="/Logout" class="nav-link">Log out</a>
                    </div>
                </div>
            </nav>
        </div>
    </header>
    <main class="main-content">
        @RenderBody()
    </main>
    <script src="~/js/script.js"></script>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>*@

project/flash/Flash/Pages/Shared/_SelectedDeck.cshtml
@using Flash.Models.ViewModels
@model DeckOnPage
@{
    string? returnUrl = Url.Page("/Decks", new 
    {
        pageNumber = Model.Page,
        searchTerm = Model.SearchTerm
    });
    Dictionary<string, string?> routeValues = new()
    {
        { "deckId", Model.Deck.Id.ToString() },
        { "returnUrl", returnUrl }
    };
}
<div class="deck-block">
    <form method="post" asp-page-handler="select" asp-all-route-data="routeValues" class="deck-selector-form">
        <button type="submit" class="page-chosen">@Model.Deck.Name</button>
    </form>
    <form method="post" asp-page-handler="delete" asp-all-route-data="routeValues">
        <button type="submit" class="button delete-button">Delete</button>
    </form> 
</div>